src/main/java/com/tlt/cdis/UsersBean.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSF/JSFManagedBean.java to edit this template
 */
package com.tlt.cdis;

import com.tlt.ejb.AdminLocal;
import com.tlt.entities.AppointmentMaster;
import com.tlt.entities.EventMaster;
import com.tlt.entities.GuideMaster;
import com.tlt.entities.PlaceCategory;
import com.tlt.entities.UserMaster;
import com.tlt.entities.UserRole;
import com.tlt.utils.Utils;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import org.primefaces.PrimeFaces;

/**
 *
 * @author kunal
 */
@Named(value = "usersBean")
@SessionScoped
public class UsersBean implements Serializable {

    @EJB
    AdminLocal ad;
    Collection<UserMaster> users;
    String userid;
    UserMaster selectedUser;
    List<UserMaster> selectedUsers;
    String role;
    Collection<GuideMaster> allGuides;
    int activeTabIndex;
    Collection<AppointmentMaster> allAppointmentsOfGuides;
    Collection<EventMaster> allEventsOfGuides;

    public UsersBean() {
        users = new ArrayList<>();
        selectedUsers = new ArrayList<>();
        userid = "";
        role = "";
        selectedUser = new UserMaster();

    }

    @PostConstruct
    public void init() {
        users = ad.getAllUsers();
    }

    public int getActiveTabIndex() {
        return activeTabIndex;
    }

    public void setActiveTabIndex(int activeTabIndex) {
        this.activeTabIndex = activeTabIndex;
    }

    public String getFormatedDate(Date date) {
        return Utils.getDateTimeFormat(date);
    }

    public String getFormatedTime(Date date) {
        return Utils.getTime12h(date);
    }

    public Collection<AppointmentMaster> getAllAppointmentsOfGuides() {
        return ad.getAppointmentsOfAllGuides();
    }

    public void setAllAppointmentsOfGuides(Collection<AppointmentMaster> allAppointmentsOfGuides) {
        this.allAppointmentsOfGuides = allAppointmentsOfGuides;
    }

    public Collection<EventMaster> getAllEventsOfGuides() {
        return ad.getEventsOfAllGuides();
    }

    public void setAllEventsOfGuides(Collection<EventMaster> allEventsOfGuides) {
        this.allEventsOfGuides = allEventsOfGuides;
    }

    public Collection<GuideMaster> getAllGuides() {
        return ad.getAllGuides();
    }

    public void setAllGuides(Collection<GuideMaster> allGuides) {
        this.allGuides = allGuides;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public Collection<UserMaster> getUsers() {
        return users;
    }

    public void setUsers(List<UserMaster> users) {
        this.users = users;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        System.out.println("UserID: " + userid);
        this.userid = userid;
    }

    public UserMaster getSelectedUser() {
        return selectedUser;
    }

    public void setSelectedUser(UserMaster selectedUser) {
        this.selectedUser = selectedUser;
    }

    public List<UserMaster> getSelectedUsers() {
        return selectedUsers;
    }

    public void setSelectedUsers(List<UserMaster> selectedUsers) {
        this.selectedUsers = selectedUsers;
    }

    public void openNew() {
        this.selectedUser = new UserMaster();
    }

    public void saveUser() {
        if (this.selectedUser.getId() == null) {
            this.selectedUser.setId(Utils.getUUID());
            ad.insertUser(selectedUser);
            this.selectedUser = null;
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("User Added"));
        }
        PrimeFaces.current().executeScript("PF('manageUserDialog').hide()");
        PrimeFaces.current().ajax().update("form:messages", "form:dt-users");
    }

    public String getDeleteButtonMessage() {
        if (hasSelectedUsers()) {
            int size = this.selectedUsers.size();
            return size > 1 ? size + " selected" : "1 selected";
        }
        return "Delete";
    }

    public boolean hasSelectedUsers() {
        return this.selectedUsers != null && !this.selectedUsers.isEmpty();
    }

    public void deleteUser() {
        try {
            ad.deleteUser(userid);
            this.users = ad.getAllUsers();
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("User Removed"));
            PrimeFaces.current().ajax().update("form:messages", "form:dt-users");
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Error Deleting User"));
            PrimeFaces.current().ajax().update("form:messages", "form:dt-users");
        }
    }

    public void deleteSelectedUsers() {
        try {
            for (UserMaster p : selectedUsers) {
                ad.deleteUser(p.getId());
            }
            selectedUsers = null;
            this.users = ad.getAllUsers();
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("User Removed"));
            PrimeFaces.current().ajax().update("form:messages", "form:dt-users");
            PrimeFaces.current().executeScript("PF('dtUser').clearFilters()");
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Error Deleting User"));
            PrimeFaces.current().executeScript("PF('dtUser').clearFilters()");
        }
    }

    public void roleChangeListener(ValueChangeEvent e) {
        this.role = String.valueOf(e.getNewValue());
        if (!this.role.equals("notSelected")) {
//            for (UserRole r : ad.getAllRoles()) {
//                if (r.getUserRolePK().getRole().equals(this.role)) {
            this.users = null;
            this.users = ad.getUsersByRoles(this.role);
//            return;
////                } else {
////                    this.users = null;
////                }
//            }
        } else {
            this.users = ad.getAllUsers();
        }
    }

}

src/main/webapp/jsf/admin/transport/Transport.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:sidebar="http://xmlns.jcp.org/jsf/composite/components/sidebar"
      xmlns:navbar="http://xmlns.jcp.org/jsf/composite/components/navbar"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Transporter's Details</title>
        <h:outputStylesheet library="css" name="primeflex.min.css"/>
        <h:outputStylesheet library="css" name="styles.css"/>
        <link rel="shortcut icon" type="image/x-icon" href="../../../images/favicon.ico"/>
    </h:head>
    <h:body class="bg-gray-200">
        <navbar:admin-navbar sideNavigationBean="#{navigationBean}"/>
        <div class="my-5 px-2">
            <div class="shadow-2 surface-card border-round-2xl p-4">
                <div class="ml-2 text-4xl text-800 font-semibold my-2">Transporters</div>
                <h:form id="form">
                    <p:growl id="messages" showDetail="true" />

                    <p:toolbar>
                        <p:toolbarGroup>
                            <p:commandButton value="New" icon="pi pi-plus" actionListener="#{transportersBean.openNew}"
                                             update=":dialogs:manage-transporter-content" oncomplete="PF('manageTransporterDialog').show()"
                                             styleClass="ui-button-success" style="margin-right: .5rem">
                                <p:resetInput target=":dialogs:manage-transporter-content" />
                            </p:commandButton>
                            <p:commandButton id="delete-transporter-button" value="#{transportersBean.deleteButtonMessage}"
                                             icon="pi pi-trash" actionListener="#{transportersBean.deleteSelectedTransporters}"
                                             styleClass="ui-button-danger" disabled="#{!transportersBean.hasSelectedTransporters()}" update="@this">
                                <p:confirm header="Confirmation" message="Delete the selected Categories?"
                                           icon="pi pi-exclamation-triangle" />
                            </p:commandButton>
                        </p:toolbarGroup>
                    </p:toolbar>

                    <p:dataTable id="dt-transporter" widgetVar="dtTransporter" var="tp" value="#{transportersBean.allTransporters}"
                                 reflow="true" styleClass="products-table text-lg" selection="#{transportersBean.selectedTransporters}"
                                 rowKey="#{tp.id}" paginator="true" rows="10" rowSelectMode="add" paginatorPosition="bottom">
                        <f:facet name="header">
                            <div class="products-table-header">
                                <span class="filter-container ui-input-icon-left"> <i class="pi pi-search"></i>
                                    <p:inputText id="globalFilter" onkeyup="PF('dtTransporter').filter()" placeholder="Search" />
                                </span>
                            </div>
                        </f:facet>

                        <p:ajax event="rowSelect" update=":form:delete-transporter-button" />
                        <p:ajax event="rowUnselect" update=":form:delete-transporter-button" />
                        <p:ajax event="rowSelectCheckbox" update=":form:delete-transporter-button" />
                        <p:ajax event="rowUnselectCheckbox" update=":form:delete-transporter-button" />
                        <p:ajax event="toggleSelect" update=":form:delete-transporter-button" />

                        <p:column selectionMode="multiple" styleClass="mr-2" exportable="false"></p:column>

                        <p:column headerText="Name" sortBy="#{tp.name}" filterBy="#{tp.name}">
                            <h:outputText value="#{tp.name}" />
                        </p:column>
                        <p:column headerText="Vehicle Number Plate" sortBy="#{tp.plateNo}" filterBy="#{tp.plateNo}">
                            <h:outputText value="#{tp.plateNo}" />
                        </p:column>
                        <p:column headerText="Contact no." sortBy="#{tp.contactNo}" filterBy="#{tp.contactNo}">
                            <h:outputText value="#{tp.contactNo}" />
                        </p:column>
                        <p:column headerText="Fare Amount" sortBy="#{tp.amount}" filterBy="#{tp.amount}">
                            <h:outputText value="#{tp.amount}" />
                        </p:column>
                        <p:column headerText="City" sortBy="#{tp.cityId}" filterBy="#{tp.cityId}">
                            <h:outputText value="#{tp.cityId.name}" />
                        </p:column>

                        <p:column exportable="false">
                            <p:commandButton action="#{transportersBean.selectTransporter()}" icon="pi pi-pencil" update=":dialogs:manage-transporter-content"
                                             oncomplete="PF('manageTransporterDialog').show()"
                                             styleClass="mr-3 edit-button rounded-button ui-button-success" process="@this">
                                <f:setPropertyActionListener target="#{transportersBean.selectedTransporter}" value="#{tp}"/>
                                <p:resetInput target=":dialogs:manage-transporter-content" />
                            </p:commandButton>
                            <p:commandButton styleClass="ui-button-danger rounded-button" action="#{transportersBean.setTransporterId(tp.id)}" icon="pi pi-trash" process="@this" oncomplete="PF('deleteTransporterDialog').show()">
                                <c:set var="tpegory" value="#{tp}" />
                                <f:setPropertyActionListener target="#{transportersBean.selectedTransporter}" value="${tp}" />
                            </p:commandButton>
                        </p:column>

                    </p:dataTable>
                </h:form>

                <h:form id="dialogs">
                    <p:dialog header="Transporter's Details" showEffect="fade" modal="true" width="450" widgetVar="manageTransporterDialog"
                              responsive="true">
                        <p:outputPanel id="manage-transporter-content" class="ui-fluid">
                            <p:messages id="valMsg" closable="true" />
                            <div class="field">
                                <p:outputLabel for="name">Name</p:outputLabel>
                                <p:inputText id="name" value="#{transportersBean.selectedTransporter.name}" 
                                             required="true" requiredMessage="Name required"/>
                            </div>
                            <div class="field">
                                <p:outputLabel for="contact">Contact No.</p:outputLabel>
                                <p:inputText id="contact" value="#{transportersBean.selectedTransporter.contactNo}" 
                                             required="true" requiredMessage="Contact no. is required"/>
                            </div>
                            <div class="field">
                                <p:outputLabel for="plateno">Vehicle Number Plate</p:outputLabel>
                                <p:inputText id="plateno" value="#{transportersBean.selectedTransporter.plateNo}" 
                                             required="true" requiredMessage="Number Plate is required"/>
                            </div>
                            <div class="field">
                                <p:outputLabel for="amount">Amount</p:outputLabel>
                                <p:inputText id="amount" value="#{transportersBean.selectedTransporter.amount}" 
                                             required="true" requiredMessage="Amount is required"/>
                            </div>
                          <div class="field">
                                <p:outputLabel for="city">City</p:outputLabel>
                                <p:autoComplete id="city" value="#{transportersBean.cityTxt}"
                                                completeMethod="#{placesBean.completeText}" scrollHeight="250"
                                                required="true" requiredMessage="City is required"
                                                />
                            </div>
                        </p:outputPanel>

                        <f:facet name="footer">
                            <p:commandButton value="Save" styleClass="mr-3 bg-purple-500 ui-button-help" icon="pi pi-check" 
                                             actionListener="#{transportersBean.saveTransporter}"
                                             update="manage-transporter-content" 
                                             process="manage-transporter-content @this" />
                            <p:commandButton value="Cancel" icon="pi pi-times" onclick="PF('manageTransporterDialog').hide()"
                                             class="mx-3 ui-button-secondary" type="button" />
                        </f:facet>
                    </p:dialog>

                    <p:confirmDialog widgetVar="deleteTransporterDialog" showEffect="fade" width="400"
                                     message="Are you sure you want to remove this Transporter?" 
                                     styleClass="text-lg font-semibold"
                                     header="Remove" severity="warn">
                        <p:commandButton value="Yes" icon="pi pi-check" 
                                         styleClass="ui-confirmdialog-yes ui-button-help" 
                                         actionListener="#{transportersBean.deleteTransporter}" 
                                         process="@this" update=":form:delete-transporter-button"
                                         oncomplete="PF('deleteTransporterDialog').hide()" />
                        <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no ui-button-flat ui-button-help" icon="pi pi-times" onclick="PF('deleteTransporterDialog').hide()" />
                    </p:confirmDialog>

                    <p:confirmDialog global="false" showEffect="fade" width="300">
                        <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="pi pi-check" />
                        <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no ui-button-secondary"
                                         icon="pi pi-times" />
                    </p:confirmDialog>
                </h:form>
            </div>
        </div>
    </h:body>

</html>