src/main/java/com/tlt/cdis/LandingBean.java
package com.tlt.cdis;

import com.maxmind.geoip2.model.CityResponse;
import static com.tlt.constants.UrlConstants.TO_CHOSEN_PLACES_FORWARD;
import com.tlt.ejb.AdminLocal;
import com.tlt.ejb.TouristLocal;
import com.tlt.entities.PlaceCategory;
import com.tlt.entities.PlaceMaster;
import com.tlt.entities.UserMaster;
import com.tlt.record.KeepRecord;
import static com.tlt.utils.GeoLocationUtil.getUserLocation;
import com.tlt.utils.Utils;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import org.primefaces.PrimeFaces;
import org.primefaces.model.map.DefaultMapModel;
import org.primefaces.model.map.LatLng;
import org.primefaces.model.map.MapModel;
import org.primefaces.model.map.Marker;

@Named(value = "landingBean")
@SessionScoped
public class LandingBean implements Serializable {

    @EJB
    AdminLocal adminLogic;
    @EJB
    TouristLocal userLogic;

    String placeName;
    Collection<PlaceMaster> recommandedPlaces;
    UserMaster currentUser;
    ArrayList<PlaceCategory> placeCategories;
    PlaceCategory selectedCategory;
    Collection<PlaceMaster> lstPlacesByCategory;

    MapBean mapBean;
    String currentLat;
    String currentLng;
    CityResponse userLocation;

    @Inject
    public LandingBean(MapBean mapBean) {
        recommandedPlaces = new ArrayList<>();
        currentUser = new UserMaster();
        placeCategories = new ArrayList<>();
        lstPlacesByCategory = new ArrayList<>();
        this.mapBean = mapBean;
    }

    public void loadMarkers() {
        userLocation = getUserLocation();
        String currentUserCity = userLocation.getCity().getName();
        String countryCode = userLocation.getCountry().getIsoCode();

        Collection<PlaceMaster> places = adminLogic.getPlacesByCity(currentUserCity, countryCode);
        MapModel<String> advancedModel = new DefaultMapModel<>();
        for (PlaceMaster p : places) {
            LatLng ll = new LatLng(Double.parseDouble(p.getLatitude()), Double.parseDouble(p.getLongitude()));
            advancedModel.addOverlay(new Marker<>(ll, p.getName(), p.getImages()));
        }
        mapBean.setAdvancedModel(advancedModel);
        PrimeFaces.current().executeScript("getLocation();");
        this.currentLat = userLocation.getLocation().getLatitude().toString();
        this.currentLng = userLocation.getLocation().getLongitude().toString();
    }

    public void loadMarkerByCategory() {
        MapModel<String> categoryModel = new DefaultMapModel<>();
        for (PlaceMaster p : lstPlacesByCategory) {
            LatLng ll = new LatLng(Double.parseDouble(p.getLatitude()), Double.parseDouble(p.getLongitude()));
            categoryModel.addOverlay(new Marker<>(ll, p.getName(), p.getImages()));
        }
        mapBean.setCategoryModel(categoryModel);
        PrimeFaces.current().executeScript("getLocation();");
    }

    @PostConstruct
    public void init() {
        loadMarkers();
    }

    public String getPlaceName() {
        return placeName;
    }

    public void setPlaceName(String placeName) {
        this.placeName = placeName;
    }

    public Collection<PlaceMaster> getRecommandedPlaces() {
        recommandedPlaces = adminLogic.getPlacesByCity(userLocation.getCity().getName(), userLocation.getCountry().getIsoCode().toString());
        ArrayList<PlaceMaster> recPlace = new ArrayList<>(recommandedPlaces);
        return recPlace.subList(recPlace.size() - 4, recPlace.size());
    }

    public void setRecommandedPlaces(Collection<PlaceMaster> recommandedPlaces) {
        this.recommandedPlaces = recommandedPlaces;
    }

    public UserMaster getCurrentUser() {
        return userLogic.findUserByUsername(String.valueOf(KeepRecord.getUsername()));
    }

    public void setCurrentUser(UserMaster currentUser) {
        this.currentUser = currentUser;
    }

    public String getCurrentLat() {
        return currentLat;
    }

    public void setCurrentLat(String currentLat) {
        this.currentLat = currentLat;
    }

    public String getCurrentLng() {
        return currentLng;
    }

    public void setCurrentLng(String currentLng) {
        this.currentLng = currentLng;
    }

    public Collection<PlaceMaster> getLstPlacesByCategory() {
        return lstPlacesByCategory;
    }

    public void setLstPlacesByCategory(Collection<PlaceMaster> lstPlacesByCategory) {
        this.lstPlacesByCategory = lstPlacesByCategory;
    }

    public PlaceCategory getSelectedCategory() {
        return selectedCategory;
    }

    public void setSelectedCategory(PlaceCategory selectedCategory) {
        this.selectedCategory = selectedCategory;
    }

    public ArrayList<PlaceCategory> getPlaceCategories() {
        if (placeCategories.size() > 0) {
            return this.placeCategories;
        }
        String currentUserCity = userLocation.getCity().getName();
        String countryCode = userLocation.getCountry().getIsoCode();
        ArrayList<PlaceCategory> placeCategoryList = new ArrayList(adminLogic.getAllPlaceCategories());

        for (PlaceCategory pc : placeCategoryList) {
            ArrayList<PlaceMaster> pm = new ArrayList<>(adminLogic.getCityPlacesByCategory(pc, currentUserCity, countryCode));
            if ((pm.size() == 0 || pm == null)) {
                continue;
            }
            placeCategories.add(pc);
        }

        return this.placeCategories;
    }

    public void setPlaceCategories(ArrayList<PlaceCategory> placeCategories) {
        this.placeCategories = placeCategories;
    }

    // This method would use in landing page search method as auto complete 
    public List<String> placesNameList(String query) {
        Collection<PlaceMaster> places = adminLogic.getAllPlaces();
        List<String> namesOfPlaces = new ArrayList<>();
        for (PlaceMaster place : places) {
            namesOfPlaces.add(place.getName());
        }
        return namesOfPlaces.stream().filter(place -> place.toLowerCase().contains(query.toLowerCase())).collect(Collectors.toList());
    }

    public void redirectToPlace() {
        try {
            Collection<PlaceMaster> places = adminLogic.getPlacesByName(placeName);
            for (PlaceMaster p : places) {
                if (p.getName().equals(placeName)) {
                    FacesContext.getCurrentInstance().getExternalContext().redirect(TO_CHOSEN_PLACES_FORWARD + "?place=" + p.getId());
                    return;
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void onCatCardSelect(PlaceCategory category) {
        String currentUserCity = userLocation.getCity().getName();
        String countryCode = userLocation.getCountry().getIsoCode();
        lstPlacesByCategory = adminLogic.getCityPlacesByCategory(category, currentUserCity, countryCode);
        selectedCategory = category;
        loadMarkerByCategory();
        PrimeFaces.current().executeScript("PF('c_dialog').show()");
        PrimeFaces.current().ajax().update(":dialog-form:category-dialog");
    }

    public String getTime(Date date) {
        return Utils.getTime12h(date);
    }

    public String getCurrentYear() {
        Calendar cal = Calendar.getInstance();
        return String.valueOf(cal.get(Calendar.YEAR));
    }
}

src/main/webapp/resources/components/footer/footer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <!-- INTERFACE -->
    <cc:interface>
    </cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>
        <f:loadBundle basename="properties.config" var="conf"/>
        <div class="footer text-white mt-4" style="background-color: #2d3548;font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif">
                <div class="container px-4 py-2">
                    <div class="grid">
                        <div class="col-12 md:col-6 px-2">
                            <div class="flex align-items-center mt-4 mb-3">
                                <div><p:graphicImage value="/images/tlt-logo.png" height="40" style="filter: grayscale(100%) invert(100%); margin-right: .6rem"/></div>
                                <div class="text-4xl font-semibold">The landmark tour</div>
                            </div>
                            <div class="px-2">Motive of this project is to guide visitors and travelers to explore places around and gain knowledge about the historic places. Our guides helps you to provide best knowledge about any places, will also help you to make your trip amazing.</div>
                        </div>
                        <div class="col-12 md:col-6">
                            <div class="text-2xl font-semibold my-4">Contact us</div>
                            <a class="flex align-items-center my-2" href="mailto:#{conf.OEMAIL}" style="text-decoration: none;color:white"><span class="material-symbols-outlined mr-2">email</span>#{conf.OEMAIL}</a>
                            <a class="flex align-items-center my-2" href="tel:#{conf.OPHONE}" style="text-decoration: none;color:white"><span class="material-symbols-outlined mr-2">phone</span>#{conf.OPHONE}</a>
                        </div>
                    </div>
                    <p:divider/>
                    <div class="my-2 text-center">Crafted by The landmark tour team &#169; | #{landingBean.currentYear}</div>
                </div>
            </div>
    </cc:implementation>
</html>